### ISSUE TITLE
Find bottle-neck in Perception code

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#557]
Currently, our PCL code is writing out very fast processing speeds, but the frame rate that we are actually receiving does not make sense in light of the processing speeds of individual functions. We'd like to test all aspects of the code that way we can see how much time each part takes and look into optimizing individual parts.

Use `high_resolution_clock::now()` to find the amount of time that elapses when a function runs, and use `cerr << "Camera frame rate: " << zed.getCurrentFPS() << "\n";` to get the actual fps that the ZED is receiving.

**Comment by niwhsa9** [comment]
![image](https://user-images.githubusercontent.com/10037572/103931068-8afc2000-50d4-11eb-9d7b-2d6366f4e51e.png)
Results for an arbitrary iteration on my system w/ Zed, AR Detect, and Obs detect. Most iterations looked similar to this. Seems like PCL viewer updates are the most expensive thing after the obs-detect pipeline. Likely because the CPU clouds have to be copied to the GPU.

**Comment by mmartin4972** [comment]
Jetson test concluded similar findings. The overall conclusion was that the viewers had a very large impact on the overall time it took for each iteration to complete. With perception_debug off our performance increased dramatically
