### ISSUE TITLE
Understand -mavx flag

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#564]
In the meson.build file we have a flag in the meson executable -mavx. This flag was added, for without it PCL's RANSAC algorithm would segfault when run. Outside of this effect we are not sure what this flag actually means, and we know that this flag needs to be removed when the code is run on the Jetson. It's important that we understand what this flag is doing, since it is not used on the Jetson and therefore won't be used in our final code, it's not good for there to be a discrepancy like this between systems.

**Comment by moosingin3space** [comment]
I believe I can answer this:

GCC's `-m` family of flags are used to determine machine-specific optimizations. Typically, when you compile for a target (since you say `needs to be removed when the code is run on the Jetson`, I'm assuming the target in this case is your development VM), GCC will generate "generic" code for that architecture. In the case of your development VM, it is choosing to generate code for `x86-64`, or according to their manual [1]:
> A generic CPU with 64-bit extensions.

You can have GCC generate code optimized for a particular CPU by using the `-m` family. In the specific case of this flag (`-mavx`), GCC is enabling support for the AVX family of CPU extensions. I haven't taken a look at PCL's codebase, but it's possible it uses GCC intrinsic functions [2] to directly use AVX for a performance gain.

Note, however, that AVX extensions are only for x86 architecture CPUs. The Jetson is based on the 64-bit ARM for Applications (called either AArch64 or arm64, based on who you're talking to) architecture, which does not have AVX. (Instead, AArch64 defines a similar extension called NEON.) This is why the flag isn't used on the Jetson. 

Hope this is a sufficient explanation.

[1]: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
[2]: https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html#x86-Built-in-Functions

**Comment by niwhsa9** [comment]
@moosingin3space thank you :)!
